spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=salma123??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
jwt.secret=C3kLaL0Tke/Nxe2lgEURGCc8o5zIgumexcZlr9YoOcI=
jwt.expiration=86400000
app.seed.admin.username=admin
app.seed.admin.password=admin123
app.seed.superadmin.username=superadmin
app.seed.superadmin.password=superadmin123
app.leave.public-holidays.fixed=01-01,01-11,01-14,05-01,07-30,08-14,08-20,08-21,11-06,11-18
app.leave.public-holidays.exact=

